<?php

return [
    'all' => [
        'id',
        'producer_id',
        'producer_name',
        'part_id',
        'part_name',
        'part_number',
        'producer_part_number',
        'cat_level_1',
        'cat_level_2',
        'cat_level_3',
        'cat_level_4',
        'cat_level_5',
        'group',
        'd1',
        'd2',
        'd3',
        'd4',
//        'd5',
//        'l1',
//        'l2',
//        'l3',
//        'l4',
//        'l5',
//        'D1',
//        'D2',
//        'D3',
//        'D4',
//        'D5',
//        'L1',
//        'L2',
//        'L3',
//        'L4',
//        'L5',
        'A',
        'weight',
        'cutting_material',
        'surface',
        //'vat_number'
        'full_record'
    ],

    'reference_id' => [
        'part_id'
    ],

    'to_update' => [
        'producer_id',
        'producer_name',
        'part_name',
        'part_number',
        'producer_part_number',
        'cat_level_1',
        'cat_level_2',
        'cat_level_3',
        'cat_level_4',
        'cat_level_5',
        'group',
        'd1',
        'd2',
        'd3',
        'd4',
//        'd5',
//        'l1',
//        'l2',
//        'l3',
//        'l4',
//        'l5',
//        'D1',
//        'D2',
//        'D3',
//        'D4',
//        'D5',
//        'L1',
//        'L2',
//        'L3',
//        'L4',
//        'L5',
        'A',
        'weight',
        'cutting_material',
        'surface',
        //'vat_number',
        'full_record'
    ],

    'part_index' => [
        'producer_id',
        'producer_name',
        'part_name',
        'part_number',
        'producer_part_number',
        'cat_level_1',
        'cat_level_2',
        'cat_level_3',
        'cat_level_4',
        'cat_level_5',
        'group',
        'd1',
        'd2',
        'd3',
        'd4',
        'd5',
        'l1',
        'l2',
        'l3',
        'l4',
        'l5',
        '_d1',
        '_d2',
        '_d3',
        '_d4',
        '_d5',
        '_l1',
        '_l2',
        '_l3',
        '_l4',
        '_l5',
        '_a',
        'weight',
        'cutting_material',
        'surface',
        'vat_number'
    ],
];
